title: Data Science Portfolio - Jeffrey Joy
description: Pursuing Masters in Data Science at University of Arizona || PGP In Artificial Intelligence and Machine Learning at INSOFE || Data Scientist Trainee at TuringMinds.Ai
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
